console.log(typeof 'string')
console.log(typeof 12)
console.log(typeof true)
console.log(typeof undefined)
console.log(typeof null)
console.log(typeof Symbol())
console.log(typeof BigInt(10))

console.log(typeof {})
console.log(typeof [])
console.log(typeof new Date())
console.log(typeof /\d/)
console.log(typeof console.log)